---
- name: Install Apache
  hosts: All

  tasks:
    - name: Install Apache
      command: yum install --quiet -y httpd http-devel
    - name: Copy configuration files.
      command: >
        cp httpd.conf /etc/httpd/conf/httpd.conf
    - command: >
      cp httpd-vhosts /etc/httpd/conf/httpd-vhosts.conf
    - name: Start Apache and configure it to run on boot
      command: service httpd start
    - command: chkconfig httpd on
