---
- name: Install Apache
  hosts: all
  become: true

  pre_tasks:
    - name: Load variable files. 
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/apache_{{ ansible_os_family }}.yml"
        - "vars/apache_default.yml"

  handlers:
    - name: restart apache
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - apache_service
    

  tasks:
   - import_tasks: tasks/apache.yml
   