---
- name: Install EPEL repo. 
  yum:
    name: epel-release
    state: present

- name: Ensure firewalld is stopped. 
  service: 
    name: firewalld
    state: stopped

- name: Install Node.js and npm
  yum:
    name: npm
    state: present
    enablerepo: epel
  
- name: Install Forever (to run our Node.js app).
  npm:
    name: forever
    global: yes
    state: present